title: Andy's Glass
description: Stained Glass Artist from Leeds

logo: "/logo.jpg"

#aux_links:
#  "Visit my SumUp shop!":
#    "//andys-glass.sumup.link/"
#aux_links_new_tab: true

#nav_external_links:
#  - title: Visit my SumUp shop!
#    url: https://andys-glass.sumup.link/

remote_theme: pmarsceill/just-the-docs
color_scheme: "light"

# url: https://andy.merckel.uk

# Use the following plug-ins
plugins:
  - jekyll-remote-theme

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
